'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useSession } from 'next-auth/react';
import { Button } from '@/components/ui/button';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import dynamic from 'next/dynamic';

// Dynamically import Globe to avoid SSR issues with Three.js
const Globe = dynamic(() => import('@/components/Globe').then(mod => mod.Globe), {
  ssr: false,
  loading: () => <div className="absolute inset-0" />,
});

const securityChecks = [
  { name: 'RLS Policies', description: 'Supabase security' },
  { name: 'API Keys', description: 'Secret detection' },
  { name: 'SQL Injection', description: 'Database security' },
  { name: 'XSS', description: 'Frontend security' },
  { name: 'Auth Issues', description: 'Access control' },
  { name: 'IDOR', description: 'Object references' },
];

const features = [
  {
    title: 'Instant Analysis',
    description: 'Paste your repo URL and get results in seconds. No setup, no configuration required.',
    icon: (
      <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    ),
    gradient: 'from-amber-500 to-orange-600',
  },
  {
    title: 'AI-Aware Scanning',
    description: 'Specifically tuned for code generated by Bolt, Lovable, v0, and Claude Code.',
    icon: (
      <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
      </svg>
    ),
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    title: 'Actionable Fixes',
    description: 'Get specific code suggestions to fix each vulnerability with before/after examples.',
    icon: (
      <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
    gradient: 'from-emerald-500 to-teal-600',
  },
  {
    title: '40+ Security Checks',
    description: 'Comprehensive coverage including RLS, secrets, injections, auth, and more.',
    icon: (
      <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
      </svg>
    ),
    gradient: 'from-violet-500 to-purple-600',
  },
];

const stats = [
  { value: '40+', label: 'Security Checks' },
  { value: '10K+', label: 'Repos Scanned' },
  { value: '50K+', label: 'Vulns Found' },
  { value: '<10s', label: 'Scan Time' },
];

interface GitHubRepo {
  id: number;
  name: string;
  full_name: string;
  private: boolean;
  html_url: string;
  description: string | null;
  updated_at: string;
}

export default function HomePage() {
  const { data: session, status } = useSession();
  const [repoUrl, setRepoUrl] = useState('');
  const [githubToken, setGithubToken] = useState('');
  const [showTokenInput, setShowTokenInput] = useState(false);
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [privateRepos, setPrivateRepos] = useState<GitHubRepo[]>([]);
  const [loadingRepos, setLoadingRepos] = useState(false);
  const [showPrivateRepos, setShowPrivateRepos] = useState(false);
  const [reposError, setReposError] = useState('');
  const router = useRouter();

  // Fetch private repos when user is logged in with GitHub
  const fetchPrivateRepos = async () => {
    if (!session?.accessToken || session?.user?.provider !== 'github') return;

    setLoadingRepos(true);
    setReposError('');

    try {
      const response = await fetch('/api/github/repos', {
        headers: {
          'Authorization': `Bearer ${session.accessToken}`,
        },
      });

      if (!response.ok) {
        throw new Error('Failed to fetch repositories');
      }

      const data = await response.json();
      // Filter to only show private repos - API returns { repos: [...] }
      const repos = data.repos || data;
      const privateOnly = repos.filter((repo: GitHubRepo) => repo.private);
      setPrivateRepos(privateOnly);
    } catch (err) {
      setReposError(err instanceof Error ? err.message : 'Failed to fetch repositories');
    } finally {
      setLoadingRepos(false);
    }
  };

  useEffect(() => {
    if (showPrivateRepos && session?.accessToken && session?.user?.provider === 'github') {
      fetchPrivateRepos();
    }
  }, [showPrivateRepos, session]);

  const handleSelectRepo = (repo: GitHubRepo) => {
    setRepoUrl(repo.html_url);
    setShowPrivateRepos(false);
  };

  const validateGitHubUrl = (url: string): boolean => {
    const pattern = /^https?:\/\/(www\.)?github\.com\/[^\/]+\/[^\/]+/;
    return pattern.test(url);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!repoUrl.trim()) {
      setError('Please enter a repository URL');
      return;
    }

    if (!validateGitHubUrl(repoUrl)) {
      setError('Please enter a valid GitHub repository URL');
      return;
    }

    setIsLoading(true);

    try {
      const response = await fetch('/api/scan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ repoUrl, githubToken: githubToken || undefined }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to scan repository');
      }

      sessionStorage.setItem('scanResult', JSON.stringify(data));
      router.push('/results');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main>
        {/* Hero Section - Centered Chat Interface */}
        <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden">
          {/* Animated background */}
          <div className="absolute inset-0 -z-10">
            {/* 3D Globe - Low opacity futuristic AI visualization */}
            <div className="absolute inset-0 opacity-30 pointer-events-none">
              <Globe className="w-full h-full" />
            </div>

            {/* Gradient orbs */}
            <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-blue-500/20 rounded-full blur-[120px] animate-pulse-glow" />
            <div className="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] bg-purple-500/20 rounded-full blur-[100px] animate-pulse-glow" style={{ animationDelay: '1s' }} />
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-indigo-500/10 rounded-full blur-[140px]" />

            {/* Grid pattern */}
            <div className="absolute inset-0 bg-[linear-gradient(to_right,oklch(0.5_0_0_/_0.03)_1px,transparent_1px),linear-gradient(to_bottom,oklch(0.5_0_0_/_0.03)_1px,transparent_1px)] bg-[size:4rem_4rem]" />
          </div>

          <div className="container mx-auto px-4 py-20 pt-28">
            <div className="mx-auto max-w-3xl text-center">
              {/* Main Headline */}
              <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-4">
                <span className="text-muted-foreground">What will you</span>
                <br />
                <span className="gradient-text">secure today?</span>
              </h1>

              {/* Subheadline */}
              <p className="text-lg md:text-xl text-muted-foreground max-w-xl mx-auto mb-10">
                Instant security scanning for AI-generated code. Built for{' '}
                <span className="text-foreground">Bolt.new</span>,{' '}
                <span className="text-foreground">Lovable</span>,{' '}
                <span className="text-foreground">v0</span>, and{' '}
                <span className="text-foreground">Claude Code</span>.
              </p>

              {/* Chat-style Input */}
              <div id="scanner" className="mx-auto max-w-2xl">
                <div className="relative">
                  {/* Glow effect behind input */}
                  <div className="absolute -inset-0.5 bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-600 rounded-2xl blur opacity-20 group-hover:opacity-30 transition-opacity" />

                  <form onSubmit={handleSubmit} className="relative">
                    <div className="relative bg-card rounded-2xl border border-border/50 shadow-2xl shadow-black/20 overflow-hidden">
                      {/* Input area */}
                      <div className="flex items-center gap-3 p-4">
                        <div className="flex-shrink-0 w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 via-indigo-500 to-purple-600 flex items-center justify-center">
                          <svg className="h-5 w-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                          </svg>
                        </div>
                        <input
                          type="url"
                          placeholder="Paste your GitHub repository URL..."
                          value={repoUrl}
                          onChange={(e) => {
                            setRepoUrl(e.target.value);
                            setError('');
                          }}
                          className="flex-1 bg-transparent text-foreground placeholder:text-muted-foreground text-base md:text-lg focus:outline-none"
                          disabled={isLoading}
                        />
                        <Button
                          type="submit"
                          size="lg"
                          className="flex-shrink-0 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-medium shadow-lg shadow-blue-500/25 transition-all hover:shadow-blue-500/40 px-6"
                          disabled={isLoading}
                        >
                          {isLoading ? (
                            <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                            </svg>
                          ) : (
                            <span className="flex items-center gap-2">
                              Scan
                              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                              </svg>
                            </span>
                          )}
                        </Button>
                      </div>

                      {/* Error message */}
                      {error && (
                        <div className="px-4 pb-3">
                          <div className="flex items-center gap-2 text-red-500 text-sm">
                            <svg className="h-4 w-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            {error}
                          </div>
                        </div>
                      )}

                      {/* Footer options */}
                      <div className="border-t border-border/50 px-4 py-3 bg-muted/30">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <button
                              type="button"
                              onClick={() => setShowTokenInput(!showTokenInput)}
                              className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1.5 transition-colors"
                            >
                              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
                              </svg>
                              {showTokenInput ? 'Hide' : 'Add'} token
                            </button>
                            {/* Private repos button - only show if logged in with GitHub */}
                            {session?.user?.provider === 'github' && (
                              <button
                                type="button"
                                onClick={() => setShowPrivateRepos(!showPrivateRepos)}
                                className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1.5 transition-colors"
                              >
                                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                                </svg>
                                Private repos
                              </button>
                            )}
                          </div>
                          {session?.user?.provider === 'github' ? (
                            <span className="text-xs text-emerald-500 flex items-center gap-1">
                              <svg className="h-3 w-3" fill="currentColor" viewBox="0 0 24 24">
                                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                              </svg>
                              GitHub connected
                            </span>
                          ) : (
                            <span className="text-xs text-muted-foreground">
                              Public repos only
                            </span>
                          )}
                        </div>

                        {showTokenInput && (
                          <div className="mt-3 space-y-2">
                            <input
                              type="password"
                              placeholder="ghp_xxxxxxxxxxxx"
                              value={githubToken}
                              onChange={(e) => setGithubToken(e.target.value)}
                              className="w-full h-10 px-3 rounded-lg bg-background border border-border/50 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-ring/50"
                              disabled={isLoading}
                            />
                            <p className="text-xs text-muted-foreground">
                              Optional:{' '}
                              <a
                                href="https://github.com/settings/tokens/new?scopes=repo&description=VibeSec%20Scanner"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-blue-400 hover:text-blue-300 underline-offset-2 hover:underline"
                              >
                                Create a token
                              </a>{' '}
                              to avoid rate limits.
                            </p>
                          </div>
                        )}

                        {/* Private repos dropdown */}
                        {showPrivateRepos && session?.user?.provider === 'github' && (
                          <div className="mt-3 space-y-2">
                            <div className="flex items-center justify-between">
                              <p className="text-sm font-medium text-foreground">Your Private Repositories</p>
                              <button
                                type="button"
                                onClick={fetchPrivateRepos}
                                className="text-xs text-blue-400 hover:text-blue-300"
                                disabled={loadingRepos}
                              >
                                Refresh
                              </button>
                            </div>

                            <div className="max-h-48 overflow-y-auto rounded-lg border border-border/50 bg-background">
                              {loadingRepos ? (
                                <div className="flex items-center justify-center py-8">
                                  <svg className="animate-spin h-5 w-5 text-muted-foreground" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                                  </svg>
                                </div>
                              ) : reposError ? (
                                <div className="p-4 text-sm text-red-400">{reposError}</div>
                              ) : privateRepos.length === 0 ? (
                                <div className="p-4 text-sm text-muted-foreground text-center">
                                  No private repositories found
                                </div>
                              ) : (
                                <div className="divide-y divide-border/50">
                                  {privateRepos.map((repo) => (
                                    <button
                                      key={repo.id}
                                      type="button"
                                      onClick={() => handleSelectRepo(repo)}
                                      className="w-full px-3 py-2.5 text-left hover:bg-muted/50 transition-colors"
                                    >
                                      <div className="flex items-center gap-2">
                                        <svg className="h-4 w-4 text-yellow-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                                        </svg>
                                        <span className="text-sm font-medium truncate">{repo.full_name}</span>
                                      </div>
                                      {repo.description && (
                                        <p className="text-xs text-muted-foreground mt-1 truncate pl-6">
                                          {repo.description}
                                        </p>
                                      )}
                                    </button>
                                  ))}
                                </div>
                              )}
                            </div>

                            <p className="text-xs text-muted-foreground">
                              Select a private repo to scan. Your GitHub access token is used securely.
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  </form>
                </div>
              </div>

              {/* Security checks pills */}
              <div className="mt-10 flex flex-wrap justify-center gap-2">
                {securityChecks.map((check) => (
                  <div
                    key={check.name}
                    className="group px-3 py-1.5 rounded-full bg-muted/50 border border-border/50 text-sm text-muted-foreground hover:bg-muted hover:text-foreground transition-colors cursor-default"
                  >
                    <span className="font-medium">{check.name}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Stats Section */}
        <section className="py-16 border-y border-border/50">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              {stats.map((stat) => (
                <div key={stat.label} className="text-center">
                  <div className="text-3xl md:text-4xl font-bold gradient-text">{stat.value}</div>
                  <div className="mt-1 text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-24">
          <div className="container mx-auto px-4">
            <div className="mx-auto max-w-2xl text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Security scanning built for{' '}
                <span className="gradient-text">AI code</span>
              </h2>
              <p className="text-lg text-muted-foreground">
                AI tools build fast but often skip critical security measures. VibeSec catches what they miss.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-4 max-w-4xl mx-auto">
              {features.map((feature) => (
                <div
                  key={feature.title}
                  className="group relative p-6 rounded-2xl bg-card border border-border/50 hover:border-border transition-all hover:shadow-lg"
                >
                  <div className={`inline-flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br ${feature.gradient} text-white mb-4`}>
                    {feature.icon}
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="py-24 bg-muted/30">
          <div className="container mx-auto px-4">
            <div className="mx-auto max-w-2xl text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Scan in <span className="gradient-text">three steps</span>
              </h2>
              <p className="text-lg text-muted-foreground">
                No setup, no installation, no configuration required.
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
              {[
                {
                  step: '01',
                  title: 'Paste URL',
                  description: 'Enter any public GitHub repository URL into the scanner.',
                },
                {
                  step: '02',
                  title: 'We Analyze',
                  description: '40+ security checks run in parallel. Results in under 10 seconds.',
                },
                {
                  step: '03',
                  title: 'Fix Issues',
                  description: 'Get detailed findings with exact file locations and fix suggestions.',
                },
              ].map((item, index) => (
                <div key={item.step} className="relative text-center">
                  {index < 2 && (
                    <div className="hidden md:block absolute top-8 left-[60%] w-[80%] h-px bg-gradient-to-r from-border to-transparent" />
                  )}
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500/10 to-purple-500/10 border border-border/50 mb-4">
                    <span className="text-xl font-bold gradient-text">{item.step}</span>
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{item.title}</h3>
                  <p className="text-sm text-muted-foreground">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-24 relative overflow-hidden">
          {/* Background effect */}
          <div className="absolute inset-0 -z-10">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] bg-gradient-to-r from-blue-500/20 via-indigo-500/20 to-purple-500/20 rounded-full blur-[100px]" />
          </div>

          <div className="container mx-auto px-4">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Ready to ship <span className="gradient-text">secure code</span>?
              </h2>
              <p className="text-lg text-muted-foreground mb-8">
                Scan your first repository for free. No signup required.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button
                  size="lg"
                  className="rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white shadow-lg shadow-blue-500/25 px-8"
                  asChild
                >
                  <Link href="#scanner">
                    <span className="flex items-center gap-2">
                      Start Scanning
                      <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                      </svg>
                    </span>
                  </Link>
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  className="rounded-full px-8"
                  asChild
                >
                  <Link href="/pricing">View Pricing</Link>
                </Button>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
